### ISSUE TITLE
Hetzner iGPU tutorial

### ISSUE THREAD

**Issue by snickers2k** [BackInBash/BackInBash#2]
Hey. I don't know how to contact you, so i hope it's okay here.

thanks for your article within hetzner community tutorials.
That worked pretty well with 18.04 , but sadly it isn't working with 20.04 anymore. Do you maybe have a hint on how to fix this?

**Comment by BackInBash** [comment]
Hi, what kind of server do you have? (CPU)
This isn´t a Ubuntu thing rather a grub thing.

**Comment by snickers2k** [comment]
thank you
it's the same server, i was using with 18.04 (where the tutorial did work) - nothing else changed.

the CPU is a i7-7700 
(GRUB) 2.04-1ubuntu26.9

sudo grub-mkconfig -o /boot/grub/grub.cfg
gives the following output (lots of errors?)

```
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/hetzner.cfg'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
grub-probe: warning: Couldn't find physical volume `(null)'. Some modules may be missing from core image..
/usr/sbin/grub-probe: warning: Couldn't find physical volume `(null)'. Some modules may be missing from core image..
Found linux image: /boot/vmlinuz-5.4.0-70-generic
Found initrd image: /boot/initrd.img-5.4.0-70-generic
/usr/sbin/grub-probe: warning: Couldn't find physical volume `(null)'. Some modules may be missing from core image..
/usr/sbin/grub-probe: warning: Couldn't find physical volume `(null)'. Some modules may be missing from core image..
/usr/sbin/grub-probe: warning: Couldn't find physical volume `(null)'. Some modules may be missing from core image..
/usr/sbin/grub-probe: warning: Couldn't find physical volume `(null)'. Some modules may be missing from core image..
done
```
thanks

**Comment by BackInBash** [comment]
Seems like the Kernel have an issue withe the `i915` driver [see here](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1872001)

You could update your Kernel to Version 5.11 or above [as described here](https://sypalo.com/how-to-upgrade-ubuntu) 
but i don´t recommend it for production use only for testing.

good luck

**Comment by snickers2k** [comment]
thank you very much for pointing me to the right direction. 
upgrading the kernel indeed fixed it. 
thanks!
